// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package database

import (
	"time"
)

type Record struct {
	ID         int32     `json:"id"`
	Name       string    `json:"name"`
	UploadTime time.Time `json:"upload_time"`
	Numofpages int32     `json:"numofpages"`
	Size       int32     `json:"size"`
}

type Sentence struct {
	ID       int32  `json:"id"`
	Sentence string `json:"sentence"`
	Pdfid    int32  `json:"pdfid"`
}
