// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package database

import (
	"time"
)

type Record struct {
	ID         int32
	Name       string
	UploadTime time.Time
}

type Sentence struct {
	ID       int32
	Sentence string
	Pdfid    int32
}
